# Site settings
title: "Zeppelin Home"
description: "Innovative floating home solutions for modern living"
url: "https://hannesmitterer.github.io"
baseurl: "/zeppelin-"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme
theme: minima

# SEO and social
author: "Hannes Mitterer"
social:
  name: "Zeppelin Home"
  links:
    - "https://github.com/hannesmitterer/zeppelin-"

# Collections
collections:
  features:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - GITHUB_PAGES_SETUP.md
  - .bundle/
  - .github-pages-cache/

# Include directories that might be ignored by default
include:
  - .htaccess
  - _pages